#!/bin/bash

if [ "$#" -eq 0 ]; then
	echo "Available network interfaces:"
	echo $(ls --color /sys/class/net | sed '/lo/d')
	echo -n "Enter the name of the network interface: "
	read userInput
else
	userInput=$1;
fi

currentHex="$(ip addr show wlp1s0 | grep link/ether | tr -s ' ' | cut -d ' ' -f3)"
echo $currentHex
tempString="$(sudo cat /dev/urandom | tr -cd 'a-f0-9' | head -c 10)"
randomHex=${currentHex:0:3}
for (( i=0; i<${#tempString}; i++)); do
	randomHex+=${tempString:$i:1}
	if [ $((i%2)) -eq 1 ]; then
		randomHex+=":";	
	fi
done
randomHex=${randomHex::-1}
echo $randomHex
sudo ip link set dev $userInput down;
sudo ip link set dev $userInput address $randomHex && sudo ip link set dev $userInput up
echo "All done!"
exit 0
